#!/bin/sh
set -e

# Railway/Render cung cấp biến PORT
if [ -n "$PORT" ]; then
  sed -i "s/8080/$PORT/g" /usr/local/tomcat/conf/server.xml
fi

# Ghi config vào file setenv.sh (Tomcat đọc khi start) - tránh & và ký tự đặc biệt làm vỡ CATALINA_OPTS
_ENVFILE="/usr/local/tomcat/bin/setenv.sh"
echo '#!/bin/sh' > "$_ENVFILE"
echo '# Generated by docker-entrypoint.sh' >> "$_ENVFILE"

_OPTS=""
[ -n "$FRONTEND_BASE_URL" ] && _OPTS="$_OPTS -Dfrontend.baseUrl=$FRONTEND_BASE_URL"
if [ -n "$BACKEND_BASE_URL" ]; then
  _BASE="$BACKEND_BASE_URL"
  case "$_BASE" in http://*) ;; https://*) ;; *) _BASE="https://$_BASE" ;; esac
  _OPTS="$_OPTS -Dvnpay.returnUrl=$_BASE/SpringMVC_SMART_HOTEL/api/callback/vnpay -Dmomo.redirectUrl=$_BASE/SpringMVC_SMART_HOTEL/api/callback/momo/guest -Dmomo.ipnUrl=$_BASE/SpringMVC_SMART_HOTEL/api/callback/momo"
fi
[ -n "$GEMINI_API_KEY" ] && _OPTS="$_OPTS -Dgemini.api.key=$GEMINI_API_KEY"
[ -n "$GEMINI_MODEL" ] && _OPTS="$_OPTS -Dgemini.model=$GEMINI_MODEL"
[ -n "$BREVO_API_KEY" ] && _OPTS="$_OPTS -Dbrevo.api.key=$BREVO_API_KEY"
[ -n "$MAIL_FROM" ] && _OPTS="$_OPTS -Dmail.from=$MAIL_FROM"
[ -n "$MAIL_FROM_NAME" ] && _OPTS="$_OPTS -Dmail.from.name=$MAIL_FROM_NAME"
[ -n "$MAIL_USER" ] && _OPTS="$_OPTS -Dmail.user=$MAIL_USER"
[ -n "$MAIL_PASS" ] && _OPTS="$_OPTS -Dmail.pass=$MAIL_PASS"
[ -n "$MAIL_SMTP_HOST" ] && _OPTS="$_OPTS -Dmail.smtp.host=$MAIL_SMTP_HOST"
[ -n "$MAIL_SMTP_PORT" ] && _OPTS="$_OPTS -Dmail.smtp.port=$MAIL_SMTP_PORT"
[ -n "$MOMO_PARTNER_CODE" ] && _OPTS="$_OPTS -Dmomo.partnerCode=$MOMO_PARTNER_CODE"
[ -n "$MOMO_ACCESS_KEY" ] && _OPTS="$_OPTS -Dmomo.accessKey=$MOMO_ACCESS_KEY"
[ -n "$MOMO_SECRET_KEY" ] && _OPTS="$_OPTS -Dmomo.secretKey=$MOMO_SECRET_KEY"
[ -n "$VNPAY_TMN_CODE" ] && _OPTS="$_OPTS -Dvnpay.tmnCode=$VNPAY_TMN_CODE"
[ -n "$VNPAY_HASH_SECRET" ] && _OPTS="$_OPTS -Dvnpay.hashSecret=$VNPAY_HASH_SECRET"
[ -n "$GOOGLE_CLIENT_ID" ] && _OPTS="$_OPTS -Dclient_id=$GOOGLE_CLIENT_ID"
[ -n "$GOOGLE_CLIENT_SECRET" ] && _OPTS="$_OPTS -Dclient_secret=$GOOGLE_CLIENT_SECRET"

# MySQL: HibernateConfigs đọc trực tiếp từ MYSQLHOST, MYSQLUSER, MYSQLPASSWORD (Railway inject)
# Không dùng -D để tránh & trong URL làm vỡ shell. Chỉ dùng -D khi có HIBERNATE_* (không dùng Railway MySQL)
if [ -z "$MYSQLHOST" ]; then
  [ -n "$HIBERNATE_CONNECTION_URL" ] && _OPTS="$_OPTS -Dhibernate.connection.url=$HIBERNATE_CONNECTION_URL"
  [ -n "$HIBERNATE_CONNECTION_USERNAME" ] && _OPTS="$_OPTS -Dhibernate.connection.username=$HIBERNATE_CONNECTION_USERNAME"
  [ -n "$HIBERNATE_CONNECTION_PASSWORD" ] && _OPTS="$_OPTS -Dhibernate.connection.password=$HIBERNATE_CONNECTION_PASSWORD"
fi

echo "export CATALINA_OPTS=\"\${CATALINA_OPTS}$_OPTS\"" >> "$_ENVFILE"
chmod +x "$_ENVFILE"

exec catalina.sh run