#!/bin/sh
set -e

# Railway/Render cung cấp biến PORT
if [ -n "$PORT" ]; then
  sed -i "s/8080/$PORT/g" /usr/local/tomcat/conf/server.xml
fi

# Ghi config vào file setenv.sh (Tomcat đọc khi start) - tránh & và ký tự đặc biệt làm vỡ CATALINA_OPTS
_ENVFILE="/usr/local/tomcat/bin/setenv.sh"
echo '#!/bin/sh' > "$_ENVFILE"
echo '# Generated by docker-entrypoint.sh' >> "$_ENVFILE"

_OPTS=""
[ -n "$FRONTEND_BASE_URL" ] && _OPTS="$_OPTS -Dfrontend.baseUrl=$FRONTEND_BASE_URL"
[ -n "$BACKEND_BASE_URL" ] && _OPTS="$_OPTS -Dvnpay.returnUrl=$BACKEND_BASE_URL/SpringMVC_SMART_HOTEL/api/callback/vnpay -Dmomo.redirectUrl=$BACKEND_BASE_URL/SpringMVC_SMART_HOTEL/api/callback/momo/guest -Dmomo.ipnUrl=$BACKEND_BASE_URL/SpringMVC_SMART_HOTEL/api/callback/momo"
[ -n "$GEMINI_API_KEY" ] && _OPTS="$_OPTS -Dgemini.api.key=$GEMINI_API_KEY"
[ -n "$MOMO_PARTNER_CODE" ] && _OPTS="$_OPTS -Dmomo.partnerCode=$MOMO_PARTNER_CODE"
[ -n "$MOMO_ACCESS_KEY" ] && _OPTS="$_OPTS -Dmomo.accessKey=$MOMO_ACCESS_KEY"
[ -n "$MOMO_SECRET_KEY" ] && _OPTS="$_OPTS -Dmomo.secretKey=$MOMO_SECRET_KEY"
[ -n "$VNPAY_TMN_CODE" ] && _OPTS="$_OPTS -Dvnpay.tmnCode=$VNPAY_TMN_CODE"
[ -n "$VNPAY_HASH_SECRET" ] && _OPTS="$_OPTS -Dvnpay.hashSecret=$VNPAY_HASH_SECRET"
[ -n "$GOOGLE_CLIENT_ID" ] && _OPTS="$_OPTS -Dclient_id=$GOOGLE_CLIENT_ID"
[ -n "$GOOGLE_CLIENT_SECRET" ] && _OPTS="$_OPTS -Dclient_secret=$GOOGLE_CLIENT_SECRET"

# MySQL: HibernateConfigs đọc trực tiếp từ MYSQLHOST, MYSQLUSER, MYSQLPASSWORD (Railway inject)
# Không dùng -D để tránh & trong URL làm vỡ shell. Chỉ dùng -D khi có HIBERNATE_* (không dùng Railway MySQL)
if [ -z "$MYSQLHOST" ]; then
  [ -n "$HIBERNATE_CONNECTION_URL" ] && _OPTS="$_OPTS -Dhibernate.connection.url=$HIBERNATE_CONNECTION_URL"
  [ -n "$HIBERNATE_CONNECTION_USERNAME" ] && _OPTS="$_OPTS -Dhibernate.connection.username=$HIBERNATE_CONNECTION_USERNAME"
  [ -n "$HIBERNATE_CONNECTION_PASSWORD" ] && _OPTS="$_OPTS -Dhibernate.connection.password=$HIBERNATE_CONNECTION_PASSWORD"
fi

echo "export CATALINA_OPTS=\"\${CATALINA_OPTS}$_OPTS\"" >> "$_ENVFILE"
chmod +x "$_ENVFILE"

exec catalina.sh run